# -*- coding: utf-8 -*-
"""Water evaporation Monitoring and Mapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tA6B7jFrhl0IynjFjTHzMUhL8Kh1E0I3
"""

import ee
import geemap
import xarray as xr
!pip install xee
import xee

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

map = geemap.Map(basemap = 'SATELLITE')
map

roi = map.draw_last_feature.geometry()
roi

lc = (
    ee.ImageCollection("MODIS/061/MCD12Q1")
    .select('LC_Type1')
    .mode()
    .eq(17)
)

map.addLayer(lc.clip(roi), {}, 'lc')

viirs = (
    ee.ImageCollection('projects/usgs-ssebop/viirs_et_v6_monthly')
    .filterDate('2015','2025')
    .map(lambda x: x.updateMask(lc).copyProperties(x, x.propertyNames()))
)

ds = xr.open_dataset(
    viirs,
    engine = 'ee',
    crs = 'EPSG:4326',
    geometry = roi,
    scale = 0.0001
)

ds = ds.sortby('time') * 1

ds.isel(time = 10).et.plot(
    x = 'lon',
    y = 'lat',
    robust = True,
    vmin = 35,
)

import numpy as np

ds_annual = ds.resample(time = 'Y').sum('time')
ds_annual = xr.where(ds_annual == 0, np.nan, ds_annual)

import matplotlib.pyplot as plt

ds_annual.et.plot.contourf(
    x = 'lon',
    y = 'lat',
    col = 'time',
    col_wrap = 5,
    robust = True,
    cmap = 'rainbow',
    vmin = 1000,
    levels = 20
)

ds_annual.mean(dim = ['lat', 'lon']).to_dataframe().to_csv('lake_evaporation.csv')

ds_annual.mean(dim = ['lat', 'lon']).to_dataframe().plot()